jobs:
  # Job 1 : Les tests unitaires classiques
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm' # Raccourci pratique pour gérer le cache automatiquement
      - run: npm ci
      - run: npm test

  # Job 2 : Les tests NestJS (tourne en même temps que le job 1)
  nestjs-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - run: npm run test:nestjs
